app/urls.py
from django.urls import path, include
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name="index"),
    path('auth/', views.initiate_auth, name='initiate_auth'),
    path('api/callback/', views.oauth_callback, name='api/callback/'),
    path('patient-details/', views.patient_details, name='patient-details'),
    path('medication-details/', views.medication_details, name='medication-details'),
    path('lab-results/', views.lab_results, name='lab-results'),
    path('vital-signs/', views.vital_signs, name='vital-signs'),
]

patient_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django SMART on FHIR</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <main>
        {% if messages %}
            {% for message in messages %}
                {% if 'success' in message.tags %}
                    <div class="alert alert-border-success alert-dismissible fade show">
                        <div class="d-flex align-items-center">
                            <div class="font-35 text-success">
                                <span class="material-icons-outlined fs-2">check_circle</span>
                            </div>
                            <div class="ms-3">
                                <div class="">{{ message }}</div>
                            </div>
                        </div>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% else %}
                    <div class="alert alert-border-danger alert-dismissible fade show">
                        <div class="d-flex align-items-center">
                            <div class="font-35 text-danger">
                                <span class="material-icons-outlined fs-2">report_gmailerrorred</span>
                            </div>
                            <div class="ms-3">
                                <div class="">{{ message }}</div>
                            </div>
                        </div>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
    <form action="{% url 'app:initiate_auth' %}" method="post">
        {% csrf_token %}

        {% if token_response %}
            {{ token_response }}
        {% else %}
            <button type="submit" class="login-button">Sign in with Epic</button>
        {% endif %}
    </form>
{% endblock %}

app/templates/app/lab-results.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
    <div class="content mt-4">
        <h1>Lab Results</h1>
        <div class="ml-2"> 
            {% for lab_result in lab_results_list %} 
                <p>{{ lab_result.test_name }} {{ lab_result.effectiveDateTime.isostring }} {{ lab_result.value }}</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/app/medication-details.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
    <div class="content mt-4">
        <h1>Medication List</h1>
        <div class="ml-2"> 
            {% for medication in medications_list %} 
                <p>{{ forloop.counter }}. {{ medication.display }}</p>
                <div class="ml-3">
                    <p>Reason: {{ medication.reason }}</p>
                    <p>Dosage: {{ medication.dosage }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/app/patient-details.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
    <div class="content mt-4">
        <h1>Hello, {{ fhir_patient.name.0.given.0 }}</h1>
        <p class="mt-2">Welcome to your Patient Record!</p>
        <p><span style="font-weight: 600;">Full Name: </span> {{ fhir_patient.name.0.text }}</p>
        <p><span style="font-weight: 600;">Epic Identifier : </span> {{ epic_identifier }}</p>
        <p><span style="font-weight: 600;">Date of birth : </span> {{ fhir_patient.birthDate.isostring }}</p>
        <p><span style="font-weight: 600;">Gender : </span> {{ fhir_patient.gender }}</p>
    </div>

    <div class="content mt-4">
        <h1>Medication List</h1>
        <div class="ml-2"> 
            {% for medication in medications_list %} 
                <p>{{ forloop.counter }}. {{ medication.display }}</p>
                <div class="ml-3">
                    <p>Reason: {{ medication.reason }}</p>
                    <p>Dosage: {{ medication.dosage }}</p>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="content mt-4">
        <h1>Lab Results</h1>
        <div class="ml-2"> 
            {% for lab_result in lab_results_list %} 
                <p>{{ lab_result.test_name }} {{ lab_result.effectiveDateTime.isostring }} {{ lab_result.value }}</p>
            {% endfor %}
        </div>
    </div>   
    
    <div class="content mt-4">
        <h1>Vital Signs</h1>
        <div class="ml-2"> 
            {% for vital_sign in vital_signs_list %} 
                <p>{{ vital_sign.test_name }} {{ vital_sign.effectiveDateTime.isostring }} {{ vital_sign.value }}{{ vital_sign.unit }}</p>
            {% endfor %}
        </div>
    </div>    
{% endblock %}

app/templates/app/vital-signs.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
    <div class="content mt-4">
        <h1>Vital Signs</h1>
        <div class="ml-2"> 
            {% for vital_sign in vital_signs_list %} 
                <p>{{ vital_sign.test_name }} {{ vital_sign.effectiveDateTime.isostring }} {{ vital_sign.value }}{{ vital_sign.unit }}</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}